### ISSUE TITLE
Text is undefined or not visible at all (example: buttons)

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#219]
![bu5](https://cloud.githubusercontent.com/assets/1053320/19518364/87d6d37c-960f-11e6-8516-ae76b3693748.png)
![bu4](https://cloud.githubusercontent.com/assets/1053320/19518363/87d62ec2-960f-11e6-9111-3cbc467f72fe.png)
![bug3](https://cloud.githubusercontent.com/assets/1053320/19518366/87d8a45e-960f-11e6-92c9-73b9070fd6fc.png)
![bug2](https://cloud.githubusercontent.com/assets/1053320/19518365/87d83f8c-960f-11e6-99ec-d4f073e0daf2.png)
![bug1](https://cloud.githubusercontent.com/assets/1053320/19518367/87e3f75a-960f-11e6-8e0b-4cc59f7c703f.png)

**Comment by Idrinth** [comment]
could you have a look at this, @Ardenian ?

**Comment by Ardenian** [comment]
I am unable to reproduce the issue with my own branch, which should be up to date, merged with a fetched origin/master. 
My first guess would be that something went wrong when doing issue #191, that's how it seems like when I take a look on w20k's Setting tab example. Looks as if it takes the arguments directly as texts instead of calling the method, as supposed.

**Comment by w20k** [comment]
Sorry, Merged the task before reading the comments :) Just looked at the code. My bad)

**Comment by w20k** [comment]
Yep, seems like bug is fixed ;) Closing!
